name: generators
version: 1.0.0

publish_to: none

environment:
  sdk: ^3.5.0
  flutter: ">=3.24.0"

dependencies:
  analyzer: ^8.1.0
  build: ^2.4.1
  collection: any
  flutter:
    sdk: flutter
  flutter_inappwebview_internal_annotations: ^1.2.0
  source_gen: ^1.5.0

dev_dependencies:
  build_runner: ^2.4.12
  build_test: ^2.2.2
  test: ^1.25.8
